- name: Arithmetic condition example
  hosts: localhost
  connection: local

  vars:
    number: 15

  tasks:
    - name: Print if number is greater than 10
      ansible.builtin.debug:
        msg: "Number is greater than 10"
      when: number > 10