---
- name: Create EC2 instances for Roboshop
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    sg_id: sg-0cbbec351f83549b4      # Replace with your SG
    ami_id: ami-022ad79f3f480ecf5    # Replace with your AMI
    instance_type: t3.micro
    environment: dev

    instances:
      - catalogue
      - mongodb

  tasks:

    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}-{{ environment }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_group: "{{ sg_id }}"
        region: ap-south-1          # Change if needed
        wait: yes
        count: 1

        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ environment }}"

      loop: "{{ instances }}"
      register: ec2_output

    - name: Print EC2 creation output
      ansible.builtin.debug:
        var: ec2_output
